---

  - name: "Copy backend files"
    become: yes
    synchronize:
      src: /root/project/backend
      dest: /home/ubuntu
      recursive: true

  - name: "Deploy code"
    become: true
    shell: |
      npm install
      npm run build
      pm2 start -f /home/ubuntu/backend/dist/main.js
      ls
    args:  
        chdir: /home/ubuntu/backend
