apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacityproject
  labels:
    app: udacityproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacityproject
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: udacityproject
    spec:
      containers:
        - name: udacityproject
          image: sakshikst/udacityproject
          command: [
            "/bin/bash",
            "npm run start"
          ]
          ports:
          - containerPort: 80
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            successThreshold: 1
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: udacityproject
spec:
  type: LoadBalancer
  selector:
    app: udacityproject
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80