version: 2.1
            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build frontend
          command: |
            cd ~/project/app
            npm install
            npm run build
      - save_cache:
          paths: [app/node_modules]
          key: frontend-build
       
  lint-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Frontend lint
          command: |
            cd ~/project/app
            npm run lint
            
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Frontend scan for vulnerabilities
          command: |
            cd ~/project/app
            npm audit fix --audit-level=critical --force

  lint-dockerfile:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
            cd ~/project/
            sudo hadolint Dockerfile

  build-docker-image:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            sudo ~/project/run_docker.sh

  upload-docker-image:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Upload Docker image
          command: |
            sudo ~/project/upload_docker.sh

  
            
workflows:
  default:
    jobs:
      - build-frontend
      - lint-frontend:
          requires: [build-frontend]
      - scan-frontend:
          requires: [build-frontend]
      - lint-dockerfile
      - build-docker-image:
          requires: [lint-dockerfile, lint-frontend, scan-frontend]
      - upload-docker-image:
          requires: [build-docker-image]
